name: Daily Commit Workflow

on:
  schedule:
    - cron: '5 3 * * *'  # Runs at 03:05 UTC every day
  workflow_dispatch:  # Allow manual run

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Update heartbeat file by 24f2007837@ds.study.iitm.ac.in
        run: |
          echo "Last updated at $(date -u)" >> heartbeat.txt

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add heartbeat.txt
          git commit -m "Daily heartbeat update [skip ci]" || echo "No changes to commit"
          git push
